Update .ansible-test.yml

diff --git a/.github/workflows/.ansible-test.yml b/.github/workflows/.ansible-test.yml
--- a/.github/workflows/.ansible-test.yml
+++ b/.github/workflows/.ansible-test.yml
@@ -1,43 +1,58 @@
-name: CI
-on:
-- pull_request
+# This is a basic workflow to help you get started with Actions
 
+name: Run Sanity Tests
+
+# Controls when the action will run. Triggers the workflow on push or pull request
+# events but only for the master branch
+on: [push]
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  sanity:
-    name: Sanity (${{ matrix.ansible }})
-    strategy:
-      matrix:
-        python_version:
-        - 3.6
-        - 3.7
-        ansible:
-        - stable-2.10
-        - devel
+  # This workflow contains a single job called "build"
+  build:
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
+
+    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-
-      - name: Check out code
-        uses: actions/checkout@v1
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+      
+      - name: setup python
+        uses: actions/setup-python@v2
         with:
-          path: ansible_collections/hpe/oneview
-
-      - name: Set up Python ${{ matrix.python_version }}
-        uses: actions/setup-python@v1
-        with:
-          python-version: ${{ matrix.python_version }}
-
+          python-version: 3.8 #install the python needed
+   
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install future
-          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+          pip install PyYAML
 
+      # Runs a single command using the runners shell
+      - name: Run UpdateJson script
+        run: |
+            output=$(python Update-JsonScript.py)
+            echo "::set-output name=changelog::$output"
+        id: step4
+
+      - name: set the workflow status              # set the workflow status if command failed
+        if: always()
+        run: |
+          if ${{ steps.step4.changelog =='True' }}; then
+             echo fine
+          else
+             exit 1
+          fi
+          
       - name: Install ansible-base (${{ matrix.ansible }})
         run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check
-
+        if: ${{ steps.step4.changelog =='True' }}
+      
       - name: Install ansible_collections.hpe.oneview
         run: ansible-galaxy collection install hpe.oneview -p ../../
+        if: ${{ steps.step4.changelog =='True' }}
 
       - name: Run sanity tests
         run: ansible-test sanity --docker -v --color --python ${{ matrix.python_version }}
+        if: ${{ steps.step4.changelog =='True' }}
